/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd.practica1s1_201213610;

import static edd.practica1s1_201213610.EDDPractica1s1_201213610.listaJ;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class AgregarJugador extends javax.swing.JFrame {

    public NodoJ aux;     
    int modificar;
    
    
    /**
     * Creates new form AgregarJugador
     */
    public AgregarJugador() {
        initComponents();
        
        this.jTextFieldNombre.setEditable(false);
        this.jTextFieldUsuario.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegresarJ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegresarJ.setText("Regresar");
        jButtonRegresarJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarJActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel1.setText("Llene los datos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, -1, -1));
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 53, 155, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 56, -1, -1));

        jLabel3.setText("Nombre Usuario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 87, -1, -1));
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 84, 155, -1));

        jButtonSiguiente.setText("Siguiente ->");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jButtonAnterior.setText("<- Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 91, -1));

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, -1));

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 110, -1));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setEnabled(false);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, -1));

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 110, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/Imagenes/PvZ.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -30, 550, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarJActionPerformed
        // TODO add your handling code here:
        Agregar agregar = new Agregar();
        agregar.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_jButtonRegresarJActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        try{
            if (listaJ.inicio!=null){
                listaJ.siguiente();
                this.jTextFieldUsuario.setText(listaJ.usu);
                this.jTextFieldNombre.setText(listaJ.nom);                
            }}catch(Exception ex){}

    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        try{
            if (listaJ.inicio!=null){
                listaJ.regresar();
                this.jTextFieldUsuario.setText(listaJ.usu);
                this.jTextFieldNombre.setText(listaJ.nom);                
            }

        }catch(Exception ex){}
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        if (listaJ.inicio!=null){

            //debloqueamos los textfield            
            this.jTextFieldUsuario.setEditable(true);
            this.jTextFieldNombre.setEditable(true);
            
            //Desbloqueamos los botones            
            this.jButtonGuardar.setEnabled(true);

            //bloqueamos los otros botones
            this.jButtonAnterior.setEnabled(false);
            this.jButtonBorrar.setEnabled(false);
            this.jButtonModificar.setEnabled(false);
            this.jButtonNuevo.setEnabled(false);
            this.jButtonSiguiente.setEnabled(false);

            modificar = 1;
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        try{
            if (listaJ.inicio!=null){
                listaJ.Borrar();
            }}catch(Exception ex){}
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed

        //bloqueamos los textfield        
        this.jTextFieldUsuario.setEditable(false);
        this.jTextFieldNombre.setEditable(false);

        //bloqueamos los botones
        this.jButtonGuardar.setEnabled(false);

        //desbloqueamos los otros botones
        this.jButtonAnterior.setEnabled(true);
        this.jButtonBorrar.setEnabled(true);
        this.jButtonModificar.setEnabled(true);
        this.jButtonNuevo.setEnabled(true);
        this.jButtonSiguiente.setEnabled(true);
        
        String usuario = this.jTextFieldUsuario.getText();
        String nombre = this.jTextFieldNombre.getText();        
        
        //String c, String i, String t, String pa, String pd,String n, String d
        if(modificar == 0){
            listaJ.incertar(nombre,usuario);
            listaJ.reco=listaJ.inicio;
        }
        else if (modificar == 1){
            listaJ.modificar(nombre,usuario);
            modificar = 0;
        }

        JOptionPane.showMessageDialog(this,"Criatura agregada "+listaJ.Length());
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed

        this.jTextFieldNombre.requestFocus();

        //debloqueamos los textfield        
        this.jTextFieldUsuario.setEditable(true);
        this.jTextFieldNombre.setEditable(true);
        
        //debloqueamos los textfield        
        this.jTextFieldNombre.setText("");
        this.jTextFieldUsuario.setText("");
        
        //Desbloqueamos los botones        
        this.jButtonGuardar.setEnabled(true);

        //bloqueamos los otros botones
        this.jButtonAnterior.setEnabled(false);
        this.jButtonBorrar.setEnabled(false);
        this.jButtonModificar.setEnabled(false);
        this.jButtonNuevo.setEnabled(false);
        this.jButtonSiguiente.setEnabled(false);

    }//GEN-LAST:event_jButtonNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonRegresarJ;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
