/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd.practica1s1_201213610;

import static edd.practica1s1_201213610.EDDPractica1s1_201213610.listaJ;
import static edd.practica1s1_201213610.EDDPractica1s1_201213610.personaje;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class AgregarPoZ extends javax.swing.JFrame {

//    ListaPoZ personaje = new ListaPoZ();  
    public NodoPoZ aux; 
    public String image="";
    int modificar;
   
    public void cargarimagen(String i){
        ImageIcon foto = new ImageIcon(i);
        Icon icono = new ImageIcon(foto.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_DEFAULT));
        jLabelImagen.setIcon(icono);
        this.repaint();
    }     
    
    
    /**
     * Creates new form AgregarPlanta
     */
    public AgregarPoZ() {
        initComponents();                
        
        this.jTextFieldClase.setEditable(false);
        this.jTextFieldDueno.setEditable(false);
        this.jTextFieldNombre.setEditable(false);
        this.jTextFieldPuntosA.setEditable(false);
        this.jTextFieldPuntosD.setEditable(false);
        this.jTextFieldTipoA.setEditable(false);
        
                
        this.jComboBoxJugadores.removeAllItems();
        
        for (int i=0; i<listaJ.Length();i++){
            NodoJ mew = listaJ.getJugador(i);            
            this.jComboBoxJugadores.addItem(mew.getUsuario());
        }       
    
        
    }           
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButtonBorrar = new javax.swing.JButton();
        jButtonRegresarP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jButtonImagen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();
        jTextFieldDueno = new javax.swing.JTextField();
        jTextFieldClase = new javax.swing.JTextField();
        jTextFieldPuntosA = new javax.swing.JTextField();
        jTextFieldPuntosD = new javax.swing.JTextField();
        jTextFieldTipoA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxJugadores = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        jDialog1.setMinimumSize(new java.awt.Dimension(600, 400));

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 80, -1));

        jButtonRegresarP.setText("Regresar");
        jButtonRegresarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarPActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 86, -1));

        jLabel1.setText("Ingrese la informacion:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 151, -1));

        jLabel3.setText("Puntos de ataque:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setText("Puntos de defensa:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabelImagen.setFocusable(false);
        jLabelImagen.setMaximumSize(new java.awt.Dimension(100, 138));
        jLabelImagen.setMinimumSize(new java.awt.Dimension(100, 138));
        jLabelImagen.setPreferredSize(new java.awt.Dimension(100, 138));
        getContentPane().add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 110, 140));

        jButtonImagen.setText("Imagen");
        jButtonImagen.setEnabled(false);
        jButtonImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImagenActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 110, -1));

        jLabel5.setText("Tipo de Ataque:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setEnabled(false);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 110, -1));

        jButtonAnterior.setText("<- Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 91, -1));

        jButtonSiguiente.setText("Siguiente ->");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 87, -1));

        jLabel6.setText("Clase de personaje:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 80, -1));
        getContentPane().add(jTextFieldDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 150, -1));
        getContentPane().add(jTextFieldClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 150, -1));
        getContentPane().add(jTextFieldPuntosA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, -1));
        getContentPane().add(jTextFieldPuntosD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, -1));
        getContentPane().add(jTextFieldTipoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 150, -1));

        jLabel8.setText("Dueño:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel9.setText("Dueños: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jComboBoxJugadores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 140, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/Imagenes/PvZ.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 490, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarPActionPerformed
        // TODO add your handling code here:
        Agregar agregar = new Agregar();
        agregar.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_jButtonRegresarPActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
              
        this.jTextFieldNombre.requestFocus();
        
        //debloqueamos los textfield
        this.jTextFieldClase.setEditable(true);
        this.jTextFieldDueno.setEditable(true);
        this.jTextFieldNombre.setEditable(true);
        this.jTextFieldPuntosA.setEditable(true);
        this.jTextFieldPuntosD.setEditable(true);
        this.jTextFieldTipoA.setEditable(true);
        
        //debloqueamos los textfield
        this.jTextFieldClase.setText("");
        this.jTextFieldDueno.setText("");
        this.jTextFieldNombre.setText("");
        this.jTextFieldPuntosA.setText("");
        this.jTextFieldPuntosD.setText("");
        this.jTextFieldTipoA.setText("");
       
        //Desbloqueamos los botones
        this.jButtonImagen.setEnabled(true);
        this.jButtonGuardar.setEnabled(true);        
        
        //bloqueamos los otros botones
        this.jButtonAnterior.setEnabled(false);
        this.jButtonBorrar.setEnabled(false);
        this.jButtonModificar.setEnabled(false);
        this.jButtonNuevo.setEnabled(false);
        this.jButtonSiguiente.setEnabled(false);
      
        cargarimagen("");
        image ="";
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        
        //bloqueamos los textfield
        this.jTextFieldClase.setEditable(false);
        this.jTextFieldDueno.setEditable(false);
        this.jTextFieldNombre.setEditable(false);
        this.jTextFieldPuntosA.setEditable(false);
        this.jTextFieldPuntosD.setEditable(false);
        this.jTextFieldTipoA.setEditable(false);
        
        //bloqueamos los botones
        this.jButtonImagen.setEnabled(false);
        this.jButtonGuardar.setEnabled(false);        
        
        //desbloqueamos los otros botones
        this.jButtonAnterior.setEnabled(true);
        this.jButtonBorrar.setEnabled(true);
        this.jButtonModificar.setEnabled(true);
        this.jButtonNuevo.setEnabled(true);
        this.jButtonSiguiente.setEnabled(true);
        
        String dueno = this.jTextFieldDueno.getText();
        String clase = this.jTextFieldClase.getText();
        String nombre = this.jTextFieldNombre.getText();
        String puntosA = this.jTextFieldPuntosA.getText();
        String puntosD = this.jTextFieldPuntosD.getText();
        String tipo = this.jTextFieldTipoA.getText();                
        
        //String c, String i, String t, String pa, String pd,String n, String d
        if(modificar == 0){
           personaje.incertar(clase,image,tipo,puntosA,puntosD,nombre,dueno);
           personaje.reco=personaje.inicio;
        }
       else if (modificar == 1){
           personaje.modificar(clase,image,tipo,puntosA,puntosD,nombre,dueno);
           modificar = 0;
       }       

        JOptionPane.showMessageDialog(this,"Criatura agregada "+personaje.Length());                                       
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed

        JFileChooser seleccionar = (JFileChooser)evt.getSource();
        String command = evt.getActionCommand();
        if (command.equals(JFileChooser.APPROVE_SELECTION)){
            File archivo = seleccionar.getSelectedFile();
            image=archivo.getAbsolutePath();
            cargarimagen(image);
            jDialog1.setVisible(false);
        }else if (command.equals(JFileChooser.CANCEL_SELECTION)){
            cargarimagen("");
            jDialog1.setVisible(false);
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jButtonImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImagenActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButtonImagenActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        try{
        if (personaje.inicio!=null){
            personaje.siguiente();
            this.jTextFieldClase.setText(personaje.cla);
            this.jTextFieldDueno.setText(personaje.due);
            this.jTextFieldNombre.setText(personaje.nom);
            this.jTextFieldPuntosA.setText(personaje.puA);
            this.jTextFieldPuntosD.setText(personaje.puD);
            this.jTextFieldTipoA.setText(personaje.ti);
            cargarimagen(personaje.ima);
        }}catch(Exception ex){}
        
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        try{
        if (personaje.inicio!=null){
            personaje.Borrar();
        }}catch(Exception ex){}
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        try{
        if (personaje.inicio!=null){
            personaje.regresar();
            this.jTextFieldClase.setText(personaje.cla);
            this.jTextFieldDueno.setText(personaje.due);
            this.jTextFieldNombre.setText(personaje.nom);
            this.jTextFieldPuntosA.setText(personaje.puA);
            this.jTextFieldPuntosD.setText(personaje.puD);
            this.jTextFieldTipoA.setText(personaje.ti);
            
            cargarimagen(personaje.ima);
        }
        
        }catch(Exception ex){}
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        if (personaje.inicio!=null){
            
            //debloqueamos los textfield
            this.jTextFieldClase.setEditable(true);
            this.jTextFieldDueno.setEditable(true);
            this.jTextFieldNombre.setEditable(true);
            this.jTextFieldPuntosA.setEditable(true);
            this.jTextFieldPuntosD.setEditable(true);
            this.jTextFieldTipoA.setEditable(true);
            
            //Desbloqueamos los botones
            this.jButtonImagen.setEnabled(true);
            this.jButtonGuardar.setEnabled(true);        

            //bloqueamos los otros botones
            this.jButtonAnterior.setEnabled(false);
            this.jButtonBorrar.setEnabled(false);
            this.jButtonModificar.setEnabled(false);
            this.jButtonNuevo.setEnabled(false);
            this.jButtonSiguiente.setEnabled(false);
               
            modificar = 1;
        }        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPoZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPoZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPoZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPoZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPoZ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonImagen;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonRegresarP;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JComboBox jComboBoxJugadores;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JTextField jTextFieldClase;
    private javax.swing.JTextField jTextFieldDueno;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPuntosA;
    private javax.swing.JTextField jTextFieldPuntosD;
    private javax.swing.JTextField jTextFieldTipoA;
    // End of variables declaration//GEN-END:variables
}