/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd.practica1s1_201213610;

import static edd.practica1s1_201213610.EDDPractica1s1_201213610.listaJ;
import static edd.practica1s1_201213610.EDDPractica1s1_201213610.contz;
import static edd.practica1s1_201213610.EDDPractica1s1_201213610.contp;
import static edd.practica1s1_201213610.EDDPractica1s1_201213610.jugp;
import static edd.practica1s1_201213610.EDDPractica1s1_201213610.jugz;

/**
 *
 * @author Daniel
 */
public class Eleccion extends javax.swing.JFrame {

    /**
     * Creates new form Eleccion
     */
    public Eleccion() {
        initComponents();
        
        
        
        this.jComboJugadorP.removeAllItems();
        this.jComboJugadorZ.removeAllItems();
        this.jComboNumeroP.removeAllItems();
        this.jComboNumeroZ.removeAllItems();
        this.jComboBoxCol.removeAllItems();
        this.jComboBoxFil.removeAllItems();
        
        for (int i=1; i<=20; i++){
            this.jComboNumeroP.addItem(i);
            this.jComboNumeroZ.addItem(i);
        }
        
        for (int i=1; i<=10; i++){
            this.jComboBoxCol.addItem(i);
            this.jComboBoxFil.addItem(i);
        }
        
//      lista de ltodos los jugadores        
        for (int i=0; i<listaJ.Length();i++){
            NodoJ mew = listaJ.getJugador(i);
            this.jComboJugadorP.addItem(mew.getUsuario());
            this.jComboJugadorZ.addItem(mew.getUsuario());
//            System.out.println(mew.getUsuario());
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonComenzar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegresarE = new javax.swing.JButton();
        jComboJugadorP = new javax.swing.JComboBox();
        jComboJugadorZ = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboNumeroP = new javax.swing.JComboBox();
        jComboNumeroZ = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxFil = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxCol = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonComenzar.setText("Comenzar Juego");
        jButtonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComenzarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 255, 120, -1));

        jLabel1.setText("Elejir opciones:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, -1, -1));

        jButtonRegresarE.setText("Regresar");
        jButtonRegresarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 255, 126, -1));

        jComboJugadorP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboJugadorP, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 83, 135, -1));

        jComboJugadorZ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboJugadorZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 83, 135, -1));

        jLabel2.setText("Jugador plantas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 58, -1, -1));

        jLabel3.setText("Jugador zombis:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 58, -1, -1));

        jLabel4.setText("Numero de plantas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 114, -1, -1));

        jLabel5.setText("Numero de zombis:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 114, -1, -1));

        jComboNumeroP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboNumeroP, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 134, 79, -1));

        jComboNumeroZ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboNumeroZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 134, 79, -1));

        jLabel7.setText("Tamaño de Tablero: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 169, -1, -1));

        jComboBoxFil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxFil, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 201, 79, -1));

        jLabel8.setText("Filas:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 204, -1, -1));

        jLabel9.setText("Columnas");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 204, -1, -1));

        jComboBoxCol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 201, 79, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/Imagenes/plants-vs-zombies.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, 490, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarEActionPerformed
        // TODO add your handling code here:
        Inicio nuevo = new Inicio();
        nuevo.setVisible(true);    
        this.dispose();               
    }//GEN-LAST:event_jButtonRegresarEActionPerformed

    private void jButtonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComenzarActionPerformed
        // TODO add your handling code here:        
        try{
        contp=this.jComboNumeroP.getSelectedIndex()+1;
        contz=this.jComboNumeroZ.getSelectedIndex()+1;
        jugz=this.jComboJugadorZ.getSelectedItem().toString();
        jugp=this.jComboJugadorP.getSelectedItem().toString();
        }catch(Exception ex){}
        
        Plataforma juego = new Plataforma();
        juego.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComenzar;
    private javax.swing.JButton jButtonRegresarE;
    private javax.swing.JComboBox jComboBoxCol;
    private javax.swing.JComboBox jComboBoxFil;
    private javax.swing.JComboBox jComboJugadorP;
    private javax.swing.JComboBox jComboJugadorZ;
    private javax.swing.JComboBox jComboNumeroP;
    private javax.swing.JComboBox jComboNumeroZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
